create database bank
use bank
CREATE TABLE CUSTOMER
(ID INT,
C_NAME NVARCHAR(50),
DOB DATE,
CONTACT_NO NVARCHAR(11),
ADDRESS NVARCHAR(100),
GENDER CHAR(5),
MAIL_ID NVARCHAR(50),
MARTIAL_STATUS VARCHAR(10),
CONSTRAINT CUST_INFO PRIMARY KEY (ID)
)
SELECT * FROM CUSTOMER
-- CUSTOMER REFERENCE INFORMATION

CREATE TABLE CUSTOMER_INFO
(ID INT,
ACC_NAME NVARCHAR(20),
ACC_NO NVARCHAR(16),
ACC_ADDRESS NVARCHAR(25),
CONSTRAINT CUST_REF_INFO PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES CUSTOMER(ID)
)
SELECT * FROM CUSTOMER_INFO

-- BANK INFORAMTION

CREATE TABLE BANK_INFO
(IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
)
SELECT * FROM BANK_INFO

-- INSERT VALUES

INSERT INTO CUSTOMER(ID, C_NAME, DOB, CONTACT_NO, ADDRESS, GENDER, MAIL_ID, MARTIAL_STATUS)
VALUES(1, 'SAHIL', '1996-09-04', '987654321', 'JALANDHAR, PUNJAB', 'M', 'SAHILKALYAN@GMAIL.COM', 'SINGLE'),
(2, 'HARPREET', '1996-10-31', '986532741', 'LAXMI NAGAR, DELHI', 'M', 'HAPPYSINGH@GMAIL.COM', 'SINGLE')

INSERT INTO CUSTOMER_INFO(ID, ACC_NAME, ACC_NO, ACC_ADDRESS)
VALUES(1, 'SAHIL', '12345678912', 'JALANDHAR, PUNJAB'),
(2, 'HARPREET', '85236974123', 'LAXMI NAGAR, DELHI')

INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME)
VALUES('SBI00040N', 'STATE BANK OF INDIA', 'SBI JANDHAR PUNJAB'),
('PNB00P50', 'PUNJAB NATIONAL BANK', ' PNB LAXMI NAGAR DELHI')
Select * From BANK_INFO
Select * From CUSTOMER_INFO
Select * From CUSTOMER



